/**
 * AI Product Filler
 * Simulates AI-powered auto-fill for product descriptions, colors, and tags.
 */

// ─── Descriptions ───────────────────────────────────────────────────────────

const DESCRIPTION_TEMPLATES: Record<string, string[]> = {
  Handbags: [
    "Crafted from premium full-grain leather, this elegant handbag features multiple interior compartments and gold-tone hardware. Designed for the modern woman who values both style and functionality, it transitions seamlessly from office to evening.",
    "This sophisticated handbag combines supple leather construction with thoughtful organization. Multiple pockets, a secure magnetic clasp, and an adjustable strap make it the perfect everyday companion for the discerning shopper.",
    "A timeless design reimagined in luxurious leather, this handbag offers generous storage with a structured silhouette. The polished metal accents and rich lining elevate every outfit effortlessly.",
  ],
  Backpacks: [
    "Built for the urban explorer, this durable backpack features a padded laptop compartment, hidden anti-theft pocket, and ergonomic straps. Weather-resistant material ensures your belongings stay safe in any condition.",
    "Combining style and practicality, this versatile backpack accommodates a 15-inch laptop, daily essentials, and more. Breathable back panel and adjustable straps provide all-day comfort for college or office use.",
    "Lightweight yet spacious, this premium backpack is designed for daily use and weekend adventures alike. Features multiple organizer pockets, water bottle holders, and a padded laptop sleeve.",
  ],
  "Tote Bags": [
    "A modern take on the classic tote, this spacious bag is crafted from durable canvas with reinforced handles. Perfect for grocery runs, beach trips, or everyday errands — it folds flat for easy storage.",
    "This oversized tote combines function and fashion with its roomy interior and chic design. Interior zip pocket keeps valuables secure, while the sturdy handles and crossbody strap offer versatile carry options.",
    "Elevate your everyday carry with this premium leather tote. Features a magnetic snap closure, slip pockets, and a key fob. From work meetings to weekend markets, this bag does it all.",
  ],
  "Travel Bags": [
    "Designed for the frequent traveler, this carry-on approved bag features a spacious main compartment, wet/dry separation pocket, and TSA-friendly design. Trolley sleeve attaches to luggage for easy airport navigation.",
    "This weekend travel bag combines elegant design with practical function. Roll-top closure, waterproof exterior, and removable shoulder strap make it perfect for short getaways or gym sessions.",
    "Pack everything you need in style with this premium travel bag. Durable hardware, lockable zippers, and a padded shoe compartment ensure your belongings arrive safe and organized.",
  ],
  Clutches: [
    "An effortlessly glamorous clutch adorned with intricate embroidery and metallic accents. Features a hidden clasp and wrist strap — ideal for weddings, parties, and festive occasions.",
    "Sleek and sophisticated, this compact clutch is crafted in faux-suede with a fold-over magnetic closure. Fits your phone, cards, and lipstick — everything you need for a night out.",
    "Turn heads with this statement clutch featuring rich beaded embellishment and a satin lining. The detachable chain strap offers hands-free convenience at events and celebrations.",
  ],
  "Shoulder Bags": [
    "A versatile shoulder bag with adjustable straps and a structured silhouette. Premium leather construction, multiple compartments, and a secure zipper closure make it ideal for work or weekend outings.",
    "This chic shoulder bag blends contemporary design with everyday practicality. Roomy interior, magnetic snap closure, and a detachable strap for crossbody wear give you styling flexibility.",
    "Crafted from soft pebbled leather with a modern structured shape, this shoulder bag offers a front slip pocket and interior organization. A perfect balance of style and convenience.",
  ],
  "Crossbody Bags": [
    "Compact yet capacious, this crossbody bag keeps your essentials close and your hands free. Adjustable strap, secure zip closure, and card-ready pockets make it perfect for travel and daily use.",
    "This lightweight crossbody is designed for the on-the-go lifestyle. Features a main zip compartment, front pocket, and adjustable strap — ideal for exploring the city hands-free.",
    "Slim and minimalist, this crossbody bag fits your phone, keys, cards, and more. Anti-scratch lining, magnetic closure, and a fully adjustable strap make it an everyday essential.",
  ],
  Wallets: [
    "A slim bifold wallet with dedicated card slots, a bill compartment, and RFID-blocking technology. Crafted from genuine leather that gets better with age — a gift-ready essential for him or her.",
    "Keep your essentials organized in this minimalist leather wallet. Twelve card slots, a zip coin pocket, and a large bill compartment in a sleek, slim profile that fits in any pocket or bag.",
    "This premium leather wallet features RFID protection, multiple card slots, and a full-length note compartment. A classic design with modern functionality for everyday carry.",
  ],
  "Duffle Bags": [
    "A spacious gym-to-weekend duffle with a ventilated shoe compartment, wet pocket, and padded shoulder strap. Durable polyester construction stands up to daily workouts and travel.",
    "Pack more, carry less — this large-capacity duffle features multiple exterior pockets, a detachable shoulder strap, and water-resistant fabric. Ideal for gym, travel, or weekend getaways.",
    "Stylish and sturdy, this leather duffle bag is the ultimate travel companion. Padded handles, lockable zipper, and a telescoping trolley sleeve make airport navigation effortless.",
  ],
  "Kids Bags": [
    "Designed for little adventurers, this ergonomic school bag features padded shoulder straps, a chest buckle for weight distribution, and fun character prints. Waterproof and easy to clean.",
    "This lightweight kids backpack is sized perfectly for school essentials. Features reflective strips for safety, a front organizer pocket, and breathable mesh back panel.",
    "Adorable and functional, this kids bag comes with a sturdy handle, adjustable straps, and plenty of pockets for books, lunch boxes, and stationery. Made from durable, BPA-free materials.",
  ],
  // Clothing
  "Men's Clothing": [
    "Crafted from premium breathable fabric, this stylish piece offers a comfortable fit for all-day wear. The contemporary cut and quality stitching make it suitable for both casual and semi-formal occasions.",
    "A wardrobe essential crafted with attention to detail. Features a comfortable fit, durable construction, and versatile styling that pairs effortlessly with various outfits.",
    "Elevate your everyday look with this premium men's piece. Made from quality materials with a modern silhouette, it transitions seamlessly from casual outings to formal settings.",
  ],
  "Women's Clothing": [
    "A beautifully crafted piece that combines comfort and elegance. The breathable fabric and flattering cut make it suitable for all-day wear, from work meetings to evening outings.",
    "Designed for the modern woman, this versatile piece offers effortless style. The quality fabric drapes beautifully and the thoughtful design flatters all body types.",
    "A timeless addition to any wardrobe, crafted in soft, breathable fabric with attention to detail. Perfect for pairing with accessories to create your unique look.",
  ],
  "Kids Clothing": [
    "Soft, durable, and adorable — this kids' outfit is made from gentle-on-skin fabric that can withstand playtime. Machine washable and pre-shrunk for lasting fit and color.",
    "Designed for active kids, this outfit combines fun prints with durable construction. The elastic waistband and easy-care fabric make dressing simple and comfortable.",
    "A cute and comfortable outfit perfect for school, play, or special occasions. Made from breathable cotton with reinforced seams for long-lasting wear.",
  ],
  "Traditional Wear": [
    "Handcrafted with intricate embroidery and rich fabric, this ethnic ensemble is perfect for weddings, festivals, and celebrations. Each piece showcases skilled artisanal craftsmanship.",
    "This stunning traditional outfit features detailed zari work, vibrant colors, and premium fabric. A celebration of heritage and craftsmanship that makes you stand out at every occasion.",
    "Beautifully crafted in rich fabric with traditional motifs, this ensemble embodies timeless elegance. Perfect for festive occasions, weddings, and cultural celebrations.",
  ],
  Sportswear: [
    "High-performance activewear designed for maximum comfort and mobility. Moisture-wicking fabric keeps you cool during intense workouts, while the ergonomic cut allows full range of motion.",
    "Built for athletes and fitness enthusiasts, this sportswear features four-way stretch fabric, flatlock seams, and breathable mesh panels. Ideal for gym, yoga, or outdoor activities.",
    "Designed to perform as hard as you do, this activewear combines style with functionality. Anti-odor technology, UV protection, and a flattering fit make it your workout essential.",
  ],
  // Footwear
  "Men's Shoes": [
    "Crafted from genuine leather with cushioned insoles and durable rubber outsoles, these shoes offer all-day comfort. The classic design transitions effortlessly from the office to formal events.",
    "Premium leather upper with breathable lining and memory foam insoles for all-day comfort. Versatile design suits both formal and smart-casual occasions.",
    "These meticulously crafted leather shoes feature goodyear-welt construction for durability. The polished finish and classic silhouette make them the perfect complement to formal attire.",
  ],
  "Women's Shoes": [
    "Elegant and comfortable, these shoes feature a cushioned footbed and non-slip outsole. The timeless design pairs beautifully with both formal and casual outfits.",
    "Crafted with comfort in mind, these stylish shoes feature padded insoles, adjustable straps, and a sturdy block heel for stability. Perfect for long days and special occasions alike.",
    "These beautiful heels combine fashion and function with padded toe box, non-slip rubber sole, and a versatile design that complements any outfit from office wear to evening attire.",
  ],
  Sandals: [
    "Handcrafted leather sandals with cushioned footbeds and adjustable ankle straps. Perfect for summer days, beach outings, and casual strolls with effortless style.",
    "These comfortable sandals feature cushioned insoles, arch support, and durable straps that mold to your foot over time. From markets to mountain paths, they go everywhere.",
    "Traditional craftsmanship meets contemporary design in these artisan sandals. Genuine leather straps, rubber outsole, and embellished detailing make every step a style statement.",
  ],
  "Sports Shoes": [
    "Engineered for performance with responsive cushioning, breathable mesh upper, and durable rubber outsole. Ideal for running, training, and high-intensity workouts.",
    "These athletic shoes feature advanced cushioning technology, a supportive midsole, and non-marking outsole. Designed to enhance performance and reduce fatigue during every workout.",
    "Lightweight and breathable, these sports shoes feature knit upper construction, responsive foam midsole, and multi-directional outsole for superior grip and performance.",
  ],
  "Kids Footwear": [
    "Designed for active kids, these shoes feature flexible soles, breathable upper, and easy velcro closure. Durable construction and fun designs make them a playground favorite.",
    "These comfortable kids' shoes feature cushioned insoles, reinforced toe box, and lightweight construction. Perfect for school, play, and adventures of all kinds.",
    "Made with soft, breathable materials and a flexible sole that supports growing feet. Easy on-off design and machine-washable upper make these shoes a parent's dream.",
  ],
  // Accessories
  Sunglasses: [
    "UV400 polarized lenses with a lightweight frame designed for all-day comfort. These stylish sunglasses reduce glare and protect your eyes while complementing any face shape.",
    "Premium acetate frame with scratch-resistant polarized lenses offering 100% UV protection. A versatile design that suits both casual outings and outdoor adventures.",
    "These designer-inspired sunglasses combine fashion-forward style with eye protection. Lightweight frame, spring hinges, and polarized lenses for a comfortable, clear view.",
  ],
  Belts: [
    "Crafted from genuine full-grain leather with a polished metal buckle. This versatile belt adds a refined finishing touch to both formal and casual outfits.",
    "Premium reversible leather belt with two metal buckle options. One belt, two looks — the perfect wardrobe investment for men and women who value quality.",
    "This durable leather belt features reinforced stitching, a classic pin-buckle, and a smooth finish. A timeless accessory that completes any formal or smart-casual ensemble.",
  ],
  Scarves: [
    "Draped in luxurious silk with a vibrant printed pattern, this scarf adds instant elegance to any outfit. Versatile enough to wear around the neck, shoulders, or hair.",
    "A lightweight yet warm cashmere blend scarf with a classic geometric pattern. Soft against the skin and generously sized for multiple styling options.",
    "This beautifully crafted stole features intricate block-print design and soft fabric. Wear it as a dupatta, shawl, or statement accessory for ethnic and western looks.",
  ],
  "Caps & Hats": [
    "A classic structured cap with an adjustable back strap and embroidered logo. Made from breathable cotton twill that keeps you cool and stylish all day.",
    "This premium unisex cap features a curved brim for sun protection, moisture-wicking sweatband, and adjustable fit. Perfect for outdoor activities, sports, and casual wear.",
    "Stylish and versatile, this headwear piece is crafted from durable material with a comfortable fit. Pairs effortlessly with casual and sporty outfits for all-day wear.",
  ],
  Ties: [
    "Woven from premium silk with a classic diagonal stripe pattern, this tie adds sophistication to any formal ensemble. The hand-rolled hem ensures a refined finish.",
    "A versatile silk tie with a timeless pattern and smooth texture. The 3-inch blade width suits standard collar styles, and the keeper loop ensures a neat knot.",
    "This elegant necktie set includes a matching pocket square in premium polyester microfiber. The vibrant pattern and quality construction make it perfect for weddings and formal events.",
  ],
  // Jewelry
  Necklaces: [
    "A stunning layered necklace featuring hand-set stones in a gold-plated setting. This statement piece catches the light beautifully and elevates both casual and formal outfits.",
    "Delicately crafted pendant necklace with a gold-plated chain and sparkling crystal centerpiece. Versatile enough for everyday wear or special occasions.",
    "This beautifully designed necklace set features intricate gold-plated work with colorful meenakari accents. A must-have for festive occasions and celebrations.",
  ],
  Earrings: [
    "These elegant drop earrings feature hand-crafted filigree work in a gold-plated setting. Lightweight and comfortable for all-day wear with a secure push-back closure.",
    "Statement jhumka earrings adorned with colorful enamel work and dangling pearls. A celebration of traditional craftsmanship perfect for ethnic and festive occasions.",
    "Versatile stud earrings featuring sparkling crystal stones in a polished gold-plated setting. The classic design transitions from office to evening effortlessly.",
  ],
  Bracelets: [
    "A beautifully crafted charm bracelet featuring delicate gold-plated links and meaningful charms. Adjustable length and lobster claw clasp ensure a comfortable, secure fit.",
    "This elegant bangle set features intricate hand-engraved patterns in polished gold-plated metal. Stack them for maximum impact or wear solo for a refined look.",
    "A handcrafted leather and metal bracelet inspired by boho aesthetics. Adjustable closure and unique artisanal design make it a statement piece for everyday wear.",
  ],
  Rings: [
    "This stunning statement ring features a pavé-set crystal centerpiece in a sleek gold-plated band. Adjustable design fits most finger sizes for comfortable everyday wear.",
    "An elegantly crafted cocktail ring with a large gemstone centerpiece and micro-pavé accents. The gold-plated finish adds a luxurious touch to festive and formal outfits.",
    "Minimalist yet meaningful, this slim band ring features a polished finish and geometric design. Stack with other rings or wear alone for understated elegance.",
  ],
  Bangles: [
    "A stunning set of hand-painted meenakari bangles in vibrant colors with gold-plated borders. Perfect for festive occasions, these bangles are a celebration of Indian craftsmanship.",
    "Handcrafted in pure brass with traditional lacquer work, this bangle set features intricate patterns. Lightweight and comfortable for daily ethnic wear or special occasions.",
    "These elegant gold-plated bangles with kundan stone settings are perfect for weddings and celebrations. The set includes multiple sizes to ensure a perfect fit.",
  ],
  // Home & Lifestyle
  "Home Decor": [
    "A beautifully crafted decorative piece that adds warmth and personality to any room. Made from sustainable materials with hand-finished detailing — a unique accent for modern interiors.",
    "This artisanal home decor item blends traditional craft techniques with contemporary design. Display it as a standalone piece or complement your existing interior aesthetic.",
    "Handcrafted with care, this decorative item serves both functional and aesthetic purposes. The natural materials and earthy tones bring an organic feel to any living space.",
  ],
  Bedding: [
    "Premium 400-thread-count cotton bedsheet set with deep pocket corners and color-fast dyes. The silky smooth feel and breathable fabric ensure a restful night's sleep in every season.",
    "This luxurious duvet cover set features a hidden zipper closure, tie strings to keep the insert in place, and matching pillowcase. Machine washable for easy care.",
    "Crafted from 100% organic cotton, this bedding set is hypoallergenic and skin-friendly. The elegant printed design adds a sophisticated touch to your bedroom decor.",
  ],
  "Kitchen Items": [
    "Premium stainless steel kitchenware with an ergonomic handle design and durable construction. Dishwasher safe and suitable for all stovetop types including induction.",
    "This versatile kitchen tool is crafted from high-grade materials for long-lasting performance. The ergonomic design reduces hand fatigue during extended cooking sessions.",
    "A chef's essential built to last, this kitchen item features professional-grade construction, precise measurements, and a heat-resistant handle for safe, comfortable use.",
  ],
  "Candles & Fragrance": [
    "Hand-poured soy wax candle with a cotton wick and premium fragrance blend. Burns cleanly for up to 45 hours, filling your space with a warm, inviting scent.",
    "This luxury scented candle is crafted in a reusable glass vessel and features a complex fragrance profile with top, middle, and base notes. A beautiful gift for any occasion.",
    "A set of three aromatic candles in coordinating scents, perfect for creating a calming atmosphere. Made from natural wax with lead-free wicks and eco-friendly packaging.",
  ],
  // Electronics
  "Mobile Accessories": [
    "This premium phone case offers military-grade drop protection with a slim profile. Precise cutouts ensure full access to all buttons and ports without adding unnecessary bulk.",
    "A versatile mobile accessory set featuring a wireless charging pad, cable organizer, and screen protector. Compatible with all major smartphone models for universal convenience.",
    "Crafted from premium materials, this phone accessory combines stylish design with reliable protection. The raised lip design protects the camera and screen from surface scratches.",
  ],
  Earphones: [
    "These premium wireless earbuds feature active noise cancellation, 30-hour battery life with the charging case, and water-resistant design. Rich bass and crystal-clear audio for an immersive listening experience.",
    "Experience studio-quality sound with these in-ear headphones featuring balanced armature drivers, detachable cable, and ergonomic design. Compatible with all devices via 3.5mm jack.",
    "Lightweight and comfortable, these earphones deliver powerful bass and crisp highs. The three-button inline remote provides easy control of music, calls, and voice assistants.",
  ],
  Smartwatches: [
    "A feature-packed smartwatch with health monitoring, GPS tracking, and 7-day battery life. Water-resistant to 50 meters with customizable watch faces and interchangeable bands.",
    "This fitness-focused smartwatch monitors heart rate, sleep quality, SpO2, and stress levels. Built-in GPS, 100+ sport modes, and a crisp AMOLED display keep you on track.",
    "Stay connected with smart notifications, take calls, and track your fitness goals with this versatile smartwatch. Compatible with iOS and Android with a stylish metal case and silicone band.",
  ],
  // Beauty & Personal Care
  Skincare: [
    "This dermatologist-tested skincare set includes a vitamin C serum, hydrating moisturizer, and gentle exfoliator. Formulated with natural extracts for brightening and anti-aging benefits.",
    "A complete skincare routine in one set, featuring cleanser, toner, serum, and moisturizer. Free from parabens and sulfates, suitable for all skin types including sensitive skin.",
    "Hydrating and nourishing, this skincare kit is packed with ingredients like hyaluronic acid, niacinamide, and botanical extracts. Transform your complexion in just 4 weeks.",
  ],
  Makeup: [
    "This comprehensive makeup kit includes foundation, blush, eyeshadow palette, and lipstick in complementary shades. Long-wearing formula stays fresh for up to 12 hours.",
    "A curated collection of long-lasting, highly pigmented makeup essentials. Cruelty-free formula with SPF protection, perfect for creating looks that go from day to evening.",
    "Professional-quality cosmetics in a travel-friendly set. Features a buildable foundation, volumizing mascara, and a versatile eyeshadow palette for endless looks.",
  ],
  Haircare: [
    "This nourishing hair care set strengthens and restores hair from root to tip. Sulfate-free formula enriched with keratin and argan oil for smooth, frizz-free results.",
    "A salon-quality hair care routine featuring shampoo, conditioner, and treatment mask. Formulated to reduce hair fall, boost volume, and add brilliant shine.",
    "Transform damaged hair with this intensive repair kit containing a protein treatment, heat protectant, and leave-in conditioner. Results visible from the first wash.",
  ],
  Perfumes: [
    "A luxurious eau de parfum with a rich fragrance profile of top notes of citrus and florals, heart notes of jasmine and rose, and base notes of sandalwood and musk.",
    "This long-lasting fragrance is inspired by nature's most beautiful botanicals. With a 12-hour sillage, it leaves a memorable impression wherever you go.",
    "A sophisticated unisex perfume featuring a fresh and woody accord. The premium bottle design makes it a perfect gift, and the long-lasting formula ensures all-day confidence.",
  ],
  // Sports & Fitness
  "Gym Equipment": [
    "Heavy-duty home gym equipment designed for commercial-grade performance. Non-slip coating, ergonomic design, and durable construction make this a gym staple that lasts years.",
    "Build strength at home with this comprehensive gym kit featuring resistance bands, dumbbells, and a workout guide. Suitable for beginners to advanced fitness enthusiasts.",
    "This premium fitness equipment is engineered for targeted muscle training. Adjustable weight increments, compact design, and a carrying case make it perfect for home and travel workouts.",
  ],
  Yoga: [
    "This premium yoga mat features a non-slip surface, extra thickness for joint support, and eco-friendly TPE material. Includes carrying strap and free access to beginner yoga guides.",
    "A complete yoga accessories set including a 6mm mat, two cork blocks, a stretch strap, and a microfiber towel. Everything you need to deepen your practice.",
    "Designed for serious practitioners, this professional-grade yoga mat offers superior grip, alignment marks, and closed-cell construction to resist moisture and odors.",
  ],
  "Outdoor Sports": [
    "Durable and versatile outdoor sports gear designed for adventure enthusiasts. Weather-resistant construction, ergonomic design, and lightweight materials for all-terrain performance.",
    "Engineered for the outdoors, this gear set features UV-resistant materials, reinforced stress points, and a compact storage solution. Ready for hiking, cycling, or camping.",
    "Professional-grade outdoor equipment that meets the demands of serious adventurers. Impact-resistant, waterproof, and lightweight — built to perform in any condition.",
  ],
  // Books & Stationery
  Books: [
    "A compelling and insightful read that challenges your thinking and broadens your perspective. This bestselling title has received critical acclaim for its depth, clarity, and practical wisdom.",
    "An essential addition to your library, this well-researched book offers valuable knowledge with engaging storytelling. Perfect for students, professionals, and curious minds alike.",
    "This thought-provoking book combines expert knowledge with real-world examples. A must-read for anyone looking to learn, grow, and gain new perspectives.",
  ],
  Notebooks: [
    "Premium quality A5 hardcover notebook with 160 dot-grid pages, lay-flat binding, and a pocket for loose pages. The ideal companion for journaling, note-taking, and creative planning.",
    "This beautifully crafted journal features cream paper, rounded corners, and a ribbon bookmark. Suitable for fountain pens, markers, and ballpoints without bleed-through.",
    "An aesthetic stationery set including a ruled notebook, sticker sheets, and a fine-point pen. Perfect for students, planners, and creative minds who love organized spaces.",
  ],
  "Art Supplies": [
    "A comprehensive artist's kit featuring professional-grade watercolors, sketch pencils, blending stumps, and canvas paper. Suitable for beginners and experienced artists alike.",
    "This premium drawing set includes 48 colored pencils, a pastel set, charcoal sticks, and a sketchbook. Perfect for portraits, landscapes, and detailed illustrations.",
    "Everything you need to start creating. This art supply kit includes mixing brushes, acrylic paints, palette knives, and a stretched canvas. Beginner and pro-friendly.",
  ],
  // Toys & Kids
  Toys: [
    "This engaging educational toy stimulates creativity and problem-solving skills in children. Made from BPA-free, non-toxic materials with smooth edges for safe play.",
    "An interactive toy that grows with your child, offering multiple play modes and educational challenges. Battery-operated with auto-shutoff, suitable for ages 3 and above.",
    "Designed to spark imagination and promote developmental skills, this toy set features colorful, durable components. Includes a parent guide with activity suggestions.",
  ],
  "Educational Games": [
    "This award-winning educational board game makes learning fun for the whole family. Teaches critical thinking, vocabulary, and math skills through engaging gameplay.",
    "An STEM-focused game that challenges children to solve puzzles and build structures. Encourages creativity and logical thinking with replayable challenges for ages 5 and up.",
    "A collaborative family game that strengthens reading and problem-solving skills. Easy rules, vibrant components, and educational content make every playthrough a learning adventure.",
  ],
  "Baby Products": [
    "Made from certified organic cotton and free from BPA, phthalates, and harsh chemicals, this baby product is designed for the safest start in life. Gentle on sensitive skin.",
    "This essential baby care item is dermatologist-tested, hypoallergenic, and suitable from birth. Easy to use, easy to clean, and designed with both parent and baby in mind.",
    "A thoughtfully designed baby essential made from soft, durable materials. The ergonomic design ensures comfort for your baby while the easy-care construction simplifies your routine.",
  ],
};

const DEFAULT_DESCRIPTION =
  "A premium quality product crafted with attention to detail and superior materials. Designed for durability, style, and everyday practicality. A perfect addition to your collection.";

// ─── Colors ─────────────────────────────────────────────────────────────────

const CATEGORY_COLORS: Record<string, string[]> = {
  Handbags: ["Black", "Brown", "Beige", "Tan", "Burgundy", "Navy"],
  Backpacks: ["Black", "Grey", "Navy", "Olive", "Brown", "Charcoal"],
  "Tote Bags": ["Beige", "Black", "Brown", "Tan", "White", "Olive"],
  "Travel Bags": ["Black", "Navy", "Grey", "Olive", "Charcoal", "Brown"],
  Clutches: ["Gold", "Silver", "Black", "Rose Gold", "Ivory", "Blush"],
  "Shoulder Bags": ["Black", "Tan", "Brown", "Camel", "Burgundy", "Grey"],
  "Crossbody Bags": ["Black", "Brown", "Tan", "Navy", "Blush", "Olive"],
  Wallets: ["Black", "Brown", "Tan", "Burgundy", "Navy", "Camel"],
  "Duffle Bags": ["Black", "Navy", "Grey", "Brown", "Olive", "Charcoal"],
  "Kids Bags": ["Blue", "Pink", "Red", "Yellow", "Purple", "Green"],
  "Men's Clothing": ["White", "Navy", "Grey", "Black", "Beige", "Blue"],
  "Women's Clothing": ["Black", "White", "Blush", "Navy", "Burgundy", "Olive"],
  "Kids Clothing": ["Blue", "Pink", "Red", "Yellow", "White", "Green"],
  "Traditional Wear": ["Red", "Gold", "Green", "Maroon", "Royal Blue", "Pink"],
  Sportswear: ["Black", "White", "Grey", "Electric Blue", "Neon Green", "Red"],
  "Men's Shoes": ["Black", "Brown", "Tan", "Navy", "Oxblood", "Grey"],
  "Women's Shoes": ["Black", "Nude", "Red", "Blush", "White", "Gold"],
  Sandals: ["Brown", "Tan", "Black", "White", "Gold", "Beige"],
  "Sports Shoes": ["Black", "White", "Grey", "Neon Green", "Blue", "Red"],
  "Kids Footwear": ["Blue", "Pink", "Red", "White", "Yellow", "Black"],
  Sunglasses: ["Black", "Tortoise", "Brown", "Gold", "Silver", "Clear"],
  Belts: ["Black", "Brown", "Tan", "Camel", "Burgundy", "Navy"],
  Scarves: ["Red", "Blue", "Beige", "Multicolor", "Black", "Ivory"],
  "Caps & Hats": ["Black", "Navy", "White", "Grey", "Olive", "Red"],
  Ties: ["Navy", "Burgundy", "Silver", "Black", "Royal Blue", "Green"],
  Necklaces: ["Gold", "Silver", "Rose Gold", "Multicolor", "Pearl White"],
  Earrings: ["Gold", "Silver", "Rose Gold", "Multicolor", "Pearl"],
  Bracelets: ["Gold", "Silver", "Rose Gold", "Multicolor", "Brown"],
  Rings: ["Gold", "Silver", "Rose Gold", "Black", "Multicolor"],
  Bangles: ["Gold", "Silver", "Multicolor", "Red", "Green"],
  "Home Decor": ["Beige", "White", "Gold", "Black", "Brown", "Terracotta"],
  Bedding: ["White", "Grey", "Blue", "Beige", "Pink", "Navy"],
  "Kitchen Items": ["Silver", "Black", "White", "Red", "Gold"],
  "Candles & Fragrance": ["White", "Ivory", "Blush", "Gold", "Black"],
  "Mobile Accessories": ["Black", "Clear", "Navy", "Rose Gold", "White"],
  Earphones: ["Black", "White", "Grey", "Rose Gold", "Blue"],
  Smartwatches: ["Black", "Silver", "Gold", "Rose Gold", "Space Grey"],
  Skincare: ["White", "Beige", "Pink", "Gold", "Clear"],
  Makeup: ["Nude", "Pink", "Red", "Berry", "Brown", "Gold"],
  Haircare: ["White", "Gold", "Black", "Pink"],
  Perfumes: ["Clear", "Amber", "Gold", "Rose", "Blue"],
  "Gym Equipment": ["Black", "Grey", "Red", "Blue", "Silver"],
  Yoga: ["Purple", "Teal", "Black", "Pink", "Blue", "Grey"],
  "Outdoor Sports": ["Black", "Olive", "Orange", "Blue", "Grey"],
  Books: ["Multicolor"],
  Notebooks: ["Black", "Brown", "Blue", "Red", "White", "Olive"],
  "Art Supplies": ["Multicolor"],
  Toys: ["Multicolor", "Red", "Blue", "Yellow", "Green"],
  "Educational Games": ["Multicolor", "Blue", "Red", "Yellow"],
  "Baby Products": ["White", "Beige", "Blue", "Pink", "Yellow"],
};

const DEFAULT_COLORS = ["Black", "Brown", "Beige"];

// ─── Tags / Keywords ─────────────────────────────────────────────────────────

const CATEGORY_TAGS: Record<string, string[]> = {
  Handbags: [
    "leather handbag",
    "women handbag",
    "designer bag",
    "premium handbag",
    "ladies bag",
    "stylish handbag",
    "office bag women",
    "trendy handbag 2025",
  ],
  Backpacks: [
    "laptop backpack",
    "college backpack",
    "travel backpack",
    "anti-theft backpack",
    "waterproof backpack",
    "daily use backpack",
    "women backpack",
    "men backpack",
  ],
  "Tote Bags": [
    "tote bag women",
    "canvas tote",
    "large tote bag",
    "shopping bag",
    "office tote",
    "leather tote",
    "reusable bag",
    "everyday bag",
  ],
  "Travel Bags": [
    "travel bag",
    "duffel bag",
    "weekend bag",
    "carry-on bag",
    "waterproof travel bag",
    "luggage bag",
    "vacation bag",
    "lightweight travel bag",
  ],
  Clutches: [
    "clutch purse",
    "party clutch",
    "wedding clutch",
    "evening bag",
    "embellished clutch",
    "festive bag",
    "women clutch",
    "bridal clutch",
  ],
  "Shoulder Bags": [
    "shoulder bag women",
    "leather shoulder bag",
    "casual shoulder bag",
    "office shoulder bag",
    "multi-compartment bag",
    "stylish shoulder bag",
    "adjustable strap bag",
    "daily use bag",
  ],
  "Crossbody Bags": [
    "crossbody bag",
    "sling bag",
    "mini crossbody",
    "hands-free bag",
    "travel sling",
    "compact crossbody",
    "women crossbody",
    "daily crossbody bag",
  ],
  Wallets: [
    "leather wallet",
    "slim wallet",
    "RFID wallet",
    "bifold wallet",
    "card holder",
    "women wallet",
    "men wallet",
    "zip wallet",
  ],
  "Duffle Bags": [
    "gym bag",
    "duffle bag",
    "sports bag",
    "travel duffle",
    "weekend bag",
    "leather duffle",
    "large sports bag",
    "gym duffel",
  ],
  "Kids Bags": [
    "kids school bag",
    "children backpack",
    "cartoon bag",
    "ergonomic school bag",
    "lightweight kids bag",
    "cute school bag",
    "waterproof kids bag",
    "primary school bag",
  ],
  "Men's Clothing": [
    "men's shirt",
    "men's fashion",
    "casual wear men",
    "formal shirt",
    "slim fit shirt",
    "cotton shirt men",
    "mens kurta",
    "men's fashion 2025",
  ],
  "Women's Clothing": [
    "women's fashion",
    "ladies dress",
    "women's kurta",
    "casual wear women",
    "women's top",
    "stylish outfit",
    "cotton kurti",
    "ladies fashion 2025",
  ],
  "Kids Clothing": [
    "kids clothes",
    "children's wear",
    "boys shirt",
    "girls dress",
    "baby clothes",
    "kids fashion",
    "cotton kids clothes",
    "school uniform",
  ],
  "Traditional Wear": [
    "ethnic wear",
    "kurta set",
    "festive wear",
    "wedding outfit",
    "traditional dress",
    "salwar kameez",
    "embroidered kurta",
    "Indian ethnic wear",
  ],
  Sportswear: [
    "activewear",
    "gym clothes",
    "workout outfit",
    "yoga pants",
    "sports bra",
    "running clothes",
    "moisture-wicking wear",
    "fitness clothing",
  ],
  "Men's Shoes": [
    "formal shoes",
    "leather shoes men",
    "oxford shoes",
    "loafers men",
    "casual shoes",
    "men's footwear",
    "office shoes",
    "derby shoes",
  ],
  "Women's Shoes": [
    "heels",
    "block heels",
    "women's pumps",
    "stiletto heels",
    "flats women",
    "ladies footwear",
    "party heels",
    "comfortable heels",
  ],
  Sandals: [
    "sandals women",
    "flat sandals",
    "kolhapuri sandals",
    "summer footwear",
    "leather sandals",
    "casual sandals",
    "traditional chappals",
    "beach sandals",
  ],
  "Sports Shoes": [
    "running shoes",
    "sneakers",
    "gym shoes",
    "athletic shoes",
    "sports footwear",
    "cushioned shoes",
    "lightweight sneakers",
    "training shoes",
  ],
  "Kids Footwear": [
    "kids shoes",
    "children sandals",
    "school shoes kids",
    "boys sneakers",
    "girls sandals",
    "velcro shoes kids",
    "durable kids footwear",
    "cute shoes for kids",
  ],
  Sunglasses: [
    "UV protection sunglasses",
    "polarized sunglasses",
    "designer shades",
    "women sunglasses",
    "men sunglasses",
    "oversized sunglasses",
    "UV400 eyewear",
    "stylish sunglasses",
  ],
  Belts: [
    "leather belt men",
    "formal belt",
    "casual belt",
    "women belt",
    "genuine leather belt",
    "reversible belt",
    "buckle belt",
    "fashion belt",
  ],
  Scarves: [
    "silk scarf",
    "printed dupatta",
    "stole women",
    "neck scarf",
    "ethnic stole",
    "cashmere scarf",
    "printed scarf",
    "fashion scarf",
  ],
  "Caps & Hats": [
    "baseball cap",
    "unisex cap",
    "sun hat",
    "embroidered cap",
    "sports cap",
    "snapback",
    "adjustable cap",
    "fashion hat",
  ],
  Ties: [
    "silk tie",
    "formal necktie",
    "men's tie",
    "wedding tie",
    "office tie",
    "designer tie",
    "woven tie",
    "tie gift set",
  ],
  Necklaces: [
    "gold necklace",
    "women necklace",
    "pendant necklace",
    "layered necklace",
    "festive jewelry",
    "gold-plated necklace",
    "bridal necklace",
    "fashion jewelry",
  ],
  Earrings: [
    "jhumka earrings",
    "stud earrings",
    "drop earrings",
    "women earrings",
    "festive earrings",
    "gold earrings",
    "ethnic earrings",
    "statement earrings",
  ],
  Bracelets: [
    "charm bracelet",
    "gold bracelet",
    "women bracelet",
    "boho bracelet",
    "fashion bracelet",
    "bangle bracelet",
    "stacking bracelet",
    "anniversary gift",
  ],
  Rings: [
    "statement ring",
    "cocktail ring",
    "women ring",
    "adjustable ring",
    "fashion ring",
    "gold ring",
    "party ring",
    "gift jewelry",
  ],
  Bangles: [
    "gold bangles",
    "bangle set",
    "meenakari bangles",
    "ethnic bangles",
    "bridal bangles",
    "festive bangles",
    "traditional bangles",
    "women jewelry",
  ],
  "Home Decor": [
    "home decor",
    "interior decoration",
    "wall decor",
    "living room decor",
    "handcrafted decor",
    "table decor",
    "aesthetic decor",
    "gifting decor",
  ],
  Bedding: [
    "bed sheet",
    "cotton bedsheet",
    "duvet cover",
    "pillow covers",
    "premium bedding",
    "home textile",
    "king size bedsheet",
    "soft bed linen",
  ],
  "Kitchen Items": [
    "kitchen utensils",
    "stainless steel cookware",
    "non-stick pan",
    "kitchen tools",
    "cooking accessories",
    "home cooking",
    "chef essentials",
    "kitchen gadgets",
  ],
  "Candles & Fragrance": [
    "scented candle",
    "soy candle",
    "home fragrance",
    "aroma candle",
    "luxury candle",
    "gift candle",
    "room decor candle",
    "aromatherapy",
  ],
  "Mobile Accessories": [
    "phone case",
    "mobile cover",
    "wireless charger",
    "screen protector",
    "phone accessories",
    "power bank",
    "cable organizer",
    "mobile gadgets",
  ],
  Earphones: [
    "earphones",
    "TWS earbuds",
    "wireless headphones",
    "noise cancelling",
    "bass earphones",
    "Bluetooth earbuds",
    "in-ear headphones",
    "gaming headset",
  ],
  Smartwatches: [
    "smartwatch",
    "fitness tracker",
    "smart band",
    "health monitor",
    "GPS watch",
    "Bluetooth watch",
    "AMOLED smartwatch",
    "wearable technology",
  ],
  Skincare: [
    "skincare routine",
    "face serum",
    "vitamin C serum",
    "moisturizer",
    "anti-aging cream",
    "glow skin",
    "natural skincare",
    "hydrating serum",
  ],
  Makeup: [
    "foundation",
    "lipstick",
    "eyeshadow",
    "makeup kit",
    "long-lasting makeup",
    "waterproof mascara",
    "blush palette",
    "beauty essentials",
  ],
  Haircare: [
    "hair growth serum",
    "anti-hairfall shampoo",
    "hair conditioner",
    "keratin treatment",
    "argan oil hair",
    "hair mask",
    "natural hair care",
    "sulfate-free shampoo",
  ],
  Perfumes: [
    "long-lasting perfume",
    "Eau de Parfum",
    "floral fragrance",
    "woody perfume",
    "unisex perfume",
    "luxury fragrance",
    "designer perfume",
    "gift perfume",
  ],
  "Gym Equipment": [
    "home gym",
    "resistance bands",
    "dumbbells",
    "weight training",
    "fitness equipment",
    "workout gear",
    "strength training",
    "gym accessories",
  ],
  Yoga: [
    "yoga mat",
    "yoga block",
    "yoga strap",
    "meditation mat",
    "non-slip yoga mat",
    "eco yoga mat",
    "yoga kit",
    "pilates accessories",
  ],
  "Outdoor Sports": [
    "outdoor gear",
    "hiking equipment",
    "camping accessories",
    "cycling gear",
    "adventure sports",
    "trekking equipment",
    "sports accessories",
    "waterproof gear",
  ],
  Books: [
    "bestseller book",
    "self-help book",
    "business book",
    "novel",
    "educational book",
    "fiction",
    "non-fiction",
    "motivational book",
  ],
  Notebooks: [
    "dotted notebook",
    "bullet journal",
    "hardcover journal",
    "A5 notebook",
    "diary",
    "planner",
    "stationery",
    "premium notebook",
  ],
  "Art Supplies": [
    "art kit",
    "watercolor set",
    "sketch pencils",
    "acrylic paints",
    "drawing set",
    "artist supplies",
    "painting kit",
    "creative art",
  ],
  Toys: [
    "kids toys",
    "educational toy",
    "safe toy",
    "STEM toy",
    "learning toy",
    "interactive toy",
    "creative toy",
    "age-appropriate toy",
  ],
  "Educational Games": [
    "board game",
    "STEM game",
    "learning game",
    "kids puzzle",
    "family game",
    "brain game",
    "educational puzzle",
    "kids activity",
  ],
  "Baby Products": [
    "baby essentials",
    "newborn kit",
    "BPA-free baby",
    "organic baby",
    "infant care",
    "baby gift set",
    "safe baby product",
    "gentle baby care",
  ],
};

const DEFAULT_TAGS = [
  "premium quality",
  "online shopping india",
  "best buy",
  "free delivery",
  "top rated product",
  "stylish design",
  "durable material",
  "trending 2025",
];

// ─── Public API ──────────────────────────────────────────────────────────────

export function generateSmartDescription(
  category: string,
  _name: string,
): string {
  const templates =
    DESCRIPTION_TEMPLATES[category] ||
    DESCRIPTION_TEMPLATES["Men's Clothing"] ||
    [];
  if (templates.length === 0) return DEFAULT_DESCRIPTION;

  return templates[Math.floor(Math.random() * templates.length)];
}

export function detectProductColors(category: string): string[] {
  const colors = CATEGORY_COLORS[category] || DEFAULT_COLORS;
  // Return 3-4 most relevant colors
  return colors.slice(0, Math.min(4, colors.length));
}

export function generateProductTags(category: string, name: string): string[] {
  const tags = CATEGORY_TAGS[category] || DEFAULT_TAGS;

  // Build a name-based tag if we have a name
  const result: string[] = [...tags.slice(0, 7)];
  if (name?.trim()) {
    const nameLower = name.toLowerCase().trim();
    result.push(nameLower);
  }

  return result.slice(0, 10);
}
