/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : string, 'quantity' : bigint }
export interface ContactInfo {
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface MaskedPaymentGateway {
  'id' : string,
  'maskedSecretKey' : string,
  'name' : string,
  'isActive' : boolean,
  'maskedApiKey' : string,
}
export interface Offer {
  'id' : string,
  'name' : string,
  'discountPercent' : bigint,
  'isActive' : boolean,
}
export interface Order {
  'id' : string,
  'status' : string,
  'createdAt' : Time,
  'user' : Principal,
  'totalAmount' : bigint,
  'items' : Array<CartItem>,
  'paymentIntentId' : string,
}
export interface PaymentGateway {
  'id' : string,
  'name' : string,
  'isActive' : boolean,
  'secretKey' : string,
  'apiKey' : string,
}
export interface Product {
  'id' : string,
  'stockQuantity' : bigint,
  'imageUrls' : Array<string>,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'discountPercent' : bigint,
  'isActive' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface ProductImage {
  'blob' : ExternalBlob,
  'productId' : string,
  'uploadedAt' : Time,
}
export interface Review {
  'id' : string,
  'userName' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'productId' : string,
  'comment' : string,
  'rating' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface ThemePreference { 'themeName' : string }
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOffer' : ActorMethod<[Offer], undefined>,
  'addPaymentGateway' : ActorMethod<[PaymentGateway], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addProductImage' : ActorMethod<[string, ExternalBlob], undefined>,
  'addReview' : ActorMethod<[Review], undefined>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'classifyImage' : ActorMethod<[string], string>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteOffer' : ActorMethod<[string], undefined>,
  'deletePaymentGateway' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[string], undefined>,
  'getActiveOffers' : ActorMethod<[], Array<Offer>>,
  'getActivePaymentGateways' : ActorMethod<[], Array<MaskedPaymentGateway>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPaymentGateways' : ActorMethod<[], Array<PaymentGateway>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getMyCart' : ActorMethod<[], Array<CartItem>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getProductImages' : ActorMethod<[string], Array<ProductImage>>,
  'getProductReviews' : ActorMethod<[string], Array<Review>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getThemePreference' : ActorMethod<[], ThemePreference>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Array<CartItem>, bigint, string], string>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setThemePreference' : ActorMethod<[ThemePreference], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOffer' : ActorMethod<[Offer], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
  'updatePaymentGateway' : ActorMethod<[PaymentGateway], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];