/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Offer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
});
export const PaymentGateway = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'secretKey' : IDL.Text,
  'apiKey' : IDL.Text,
});
export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Review = IDL.Record({
  'id' : IDL.Text,
  'userName' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'productId' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const MaskedPaymentGateway = IDL.Record({
  'id' : IDL.Text,
  'maskedSecretKey' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'maskedApiKey' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
  'paymentIntentId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProductImage = IDL.Record({
  'blob' : ExternalBlob,
  'productId' : IDL.Text,
  'uploadedAt' : Time,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ThemePreference = IDL.Record({ 'themeName' : IDL.Text });
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOffer' : IDL.Func([Offer], [], []),
  'addPaymentGateway' : IDL.Func([PaymentGateway], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addProductImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'addReview' : IDL.Func([Review], [], []),
  'addToCart' : IDL.Func([CartItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'classifyImage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'clearCart' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteOffer' : IDL.Func([IDL.Text], [], []),
  'deletePaymentGateway' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteReview' : IDL.Func([IDL.Text], [], []),
  'getActiveOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getActivePaymentGateways' : IDL.Func(
      [],
      [IDL.Vec(MaskedPaymentGateway)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPaymentGateways' : IDL.Func([], [IDL.Vec(PaymentGateway)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getMyCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'getProductImages' : IDL.Func([IDL.Text], [IDL.Vec(ProductImage)], ['query']),
  'getProductReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getThemePreference' : IDL.Func([], [ThemePreference], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Vec(CartItem), IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setThemePreference' : IDL.Func([ThemePreference], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOffer' : IDL.Func([Offer], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePaymentGateway' : IDL.Func([PaymentGateway], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Offer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
  });
  const PaymentGateway = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'secretKey' : IDL.Text,
    'apiKey' : IDL.Text,
  });
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Review = IDL.Record({
    'id' : IDL.Text,
    'userName' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'productId' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Text, 'quantity' : IDL.Nat });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const MaskedPaymentGateway = IDL.Record({
    'id' : IDL.Text,
    'maskedSecretKey' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'maskedApiKey' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
    'paymentIntentId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProductImage = IDL.Record({
    'blob' : ExternalBlob,
    'productId' : IDL.Text,
    'uploadedAt' : Time,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ThemePreference = IDL.Record({ 'themeName' : IDL.Text });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOffer' : IDL.Func([Offer], [], []),
    'addPaymentGateway' : IDL.Func([PaymentGateway], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addProductImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'addReview' : IDL.Func([Review], [], []),
    'addToCart' : IDL.Func([CartItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'classifyImage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'clearCart' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteOffer' : IDL.Func([IDL.Text], [], []),
    'deletePaymentGateway' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteReview' : IDL.Func([IDL.Text], [], []),
    'getActiveOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getActivePaymentGateways' : IDL.Func(
        [],
        [IDL.Vec(MaskedPaymentGateway)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPaymentGateways' : IDL.Func(
        [],
        [IDL.Vec(PaymentGateway)],
        ['query'],
      ),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getMyCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'getProductImages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductImage)],
        ['query'],
      ),
    'getProductReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getThemePreference' : IDL.Func([], [ThemePreference], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Vec(CartItem), IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setThemePreference' : IDL.Func([ThemePreference], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOffer' : IDL.Func([Offer], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePaymentGateway' : IDL.Func([PaymentGateway], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };